apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000 # route trafic on this to target port
      targetPort: 3000 # web running on this port on each webapp replica pod
      nodePort: 30100 # expose the service at each node's ip at a static port
